# Generated by Django 3.1.7 on 2021-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
